import { TComboboxItem } from "@udecode/plate"

export const MENTIONABLES: TComboboxItem[] = [
  { key: "0", text: "Aayla Secura" },
  { key: "1", text: "Adi Gallia" },
  {
    key: "2",
    text: "Admiral Dodd Rancit",
  },
  {
    key: "3",
    text: "Admiral Firmus Piett",
  },
  {
    key: "4",
    text: "Admiral Gial Ackbar",
  },
  { key: "5", text: "Admiral Ozzel" },
  { key: "6", text: "Admiral Raddus" },
  {
    key: "7",
    text: "Admiral Terrinald Screed",
  },
  { key: "8", text: "Admiral Trench" },
  {
    key: "9",
    text: "Admiral U.O. Statura",
  },
  { key: "10", text: "Agen Kolar" },
  { key: "11", text: "Agent Kallus" },
  {
    key: "12",
    text: "Aiolin and Morit Astarte",
  },
  { key: "13", text: "Aks Moe" },
  { key: "14", text: "Almec" },
  { key: "15", text: "Alton Kastle" },
  { key: "16", text: "Amee" },
  { key: "17", text: "AP-5" },
  { key: "18", text: "Armitage Hux" },
  { key: "19", text: "Artoo" },
  { key: "20", text: "Arvel Crynyd" },
  { key: "21", text: "Asajj Ventress" },
  { key: "22", text: "Aurra Sing" },
  { key: "23", text: "AZI-3" },
  { key: "24", text: "Bala-Tik" },
  { key: "25", text: "Barada" },
  { key: "26", text: "Bargwill Tomder" },
  { key: "27", text: "Baron Papanoida" },
  { key: "28", text: "Barriss Offee" },
  { key: "29", text: "Baze Malbus" },
  { key: "30", text: "Bazine Netal" },
  { key: "31", text: "BB-8" },
  { key: "32", text: "BB-9E" },
  { key: "33", text: "Ben Quadinaros" },
  { key: "34", text: "Berch Teller" },
  { key: "35", text: "Beru Lars" },
  { key: "36", text: "Bib Fortuna" },
  {
    key: "37",
    text: "Biggs Darklighter",
  },
  { key: "38", text: "Black Krrsantan" },
  { key: "39", text: "Bo-Katan Kryze" },
  { key: "40", text: "Boba Fett" },
  { key: "41", text: "Bobbajo" },
  { key: "42", text: "Bodhi Rook" },
  { key: "43", text: "Borvo the Hutt" },
  { key: "44", text: "Boss Nass" },
  { key: "45", text: "Bossk" },
  {
    key: "46",
    text: "Breha Antilles-Organa",
  },
  { key: "47", text: "Bren Derlin" },
  { key: "48", text: "Brendol Hux" },
  { key: "49", text: "BT-1" },
  { key: "50", text: "C-3PO" },
  { key: "51", text: "C1-10P" },
  { key: "52", text: "Cad Bane" },
  { key: "53", text: "Caluan Ematt" },
  { key: "54", text: "Captain Gregor" },
  { key: "55", text: "Captain Phasma" },
  {
    key: "56",
    text: "Captain Quarsh Panaka",
  },
  { key: "57", text: "Captain Rex" },
  { key: "58", text: "Carlist Rieekan" },
  { key: "59", text: "Casca Panzoro" },
  { key: "60", text: "Cassian Andor" },
  { key: "61", text: "Cassio Tagge" },
  { key: "62", text: "Cham Syndulla" },
  {
    key: "63",
    text: "Che Amanwe Papanoida",
  },
  { key: "64", text: "Chewbacca" },
  {
    key: "65",
    text: "Chi Eekway Papanoida",
  },
  { key: "66", text: "Chief Chirpa" },
  { key: "67", text: "Chirrut Îmwe" },
  { key: "68", text: "Ciena Ree" },
  { key: "69", text: "Cin Drallig" },
  { key: "70", text: "Clegg Holdfast" },
  { key: "71", text: "Cliegg Lars" },
  { key: "72", text: "Coleman Kcaj" },
  { key: "73", text: "Coleman Trebor" },
  { key: "74", text: "Colonel Kaplan" },
  { key: "75", text: "Commander Bly" },
  {
    key: "76",
    text: "Commander Cody (CC-2224)",
  },
  {
    key: "77",
    text: "Commander Fil (CC-3714)",
  },
  { key: "78", text: "Commander Fox" },
  { key: "79", text: "Commander Gree" },
  { key: "80", text: "Commander Jet" },
  {
    key: "81",
    text: "Commander Wolffe",
  },
  {
    key: "82",
    text: "Conan Antonio Motti",
  },
  { key: "83", text: "Conder Kyl" },
  { key: "84", text: "Constable Zuvio" },
  { key: "85", text: "Cordé" },
  { key: "86", text: "Cpatain Typho" },
  { key: "87", text: "Crix Madine" },
  { key: "88", text: "Cut Lawquane" },
  { key: "89", text: "Dak Ralter" },
  { key: "90", text: "Dapp" },
  { key: "91", text: "Darth Bane" },
  { key: "92", text: "Darth Maul" },
  { key: "93", text: "Darth Tyranus" },
  { key: "94", text: "Daultay Dofine" },
  { key: "95", text: "Del Meeko" },
  { key: "96", text: "Delian Mors" },
  { key: "97", text: "Dengar" },
  { key: "98", text: "Depa Billaba" },
  { key: "99", text: "Derek Klivian" },
  { key: "100", text: "Dexter Jettster" },
  { key: "101", text: "Dineé Ellberger" },
  { key: "102", text: "DJ" },
  { key: "103", text: "Doctor Aphra" },
  { key: "104", text: "Doctor Evazan" },
  { key: "105", text: "Dogma" },
  { key: "106", text: "Dormé" },
  { key: "107", text: "Dr. Cylo" },
  { key: "108", text: "Droidbait" },
  { key: "109", text: "Droopy McCool" },
  { key: "110", text: "Dryden Vos" },
  { key: "111", text: "Dud Bolt" },
  { key: "112", text: "Ebe E. Endocott" },
  { key: "113", text: "Echuu Shen-Jon" },
  { key: "114", text: "Eeth Koth" },
  { key: "115", text: "Eighth Brother" },
  { key: "116", text: "Eirtaé" },
  { key: "117", text: "Eli Vanto" },
  { key: "118", text: "Ellé" },
  { key: "119", text: "Ello Asty" },
  { key: "120", text: "Embo" },
  { key: "121", text: "Eneb Ray" },
  { key: "122", text: "Enfys Nest" },
  { key: "123", text: "EV-9D9" },
  { key: "124", text: "Evaan Verlaine" },
  { key: "125", text: "Even Piell" },
  { key: "126", text: "Ezra Bridger" },
  { key: "127", text: "Faro Argyus" },
  { key: "128", text: "Feral" },
  { key: "129", text: "Fifth Brother" },
  { key: "130", text: "Finis Valorum" },
  { key: "131", text: "Finn" },
  { key: "132", text: "Fives" },
  { key: "133", text: "FN-1824" },
  { key: "134", text: "FN-2003" },
  {
    key: "135",
    text: "Fodesinbeed Annodue",
  },
  { key: "136", text: "Fulcrum" },
  { key: "137", text: "FX-7" },
  { key: "138", text: "GA-97" },
  { key: "139", text: "Galen Erso" },
  { key: "140", text: "Gallius Rax" },
  {
    key: "141",
    text: 'Garazeb "Zeb" Orrelios',
  },
  {
    key: "142",
    text: "Gardulla the Hutt",
  },
  { key: "143", text: "Garrick Versio" },
  { key: "144", text: "Garven Dreis" },
  { key: "145", text: "Gavyn Sykes" },
  { key: "146", text: "Gideon Hask" },
  { key: "147", text: "Gizor Dellso" },
  { key: "148", text: "Gonk droid" },
  {
    key: "149",
    text: "Grand Inquisitor",
  },
  {
    key: "150",
    text: "Greeata Jendowanian",
  },
  { key: "151", text: "Greedo" },
  { key: "152", text: "Greer Sonnel" },
  { key: "153", text: "Grievous" },
  { key: "154", text: "Grummgar" },
  { key: "155", text: "Gungi" },
  { key: "156", text: "Hammerhead" },
  { key: "157", text: "Han Solo" },
  { key: "158", text: "Harter Kalonia" },
  { key: "159", text: "Has Obbit" },
  { key: "160", text: "Hera Syndulla" },
  { key: "161", text: "Hevy" },
  { key: "162", text: "Hondo Ohnaka" },
  { key: "163", text: "Huyang" },
  { key: "164", text: "Iden Versio" },
  { key: "165", text: "IG-88" },
  { key: "166", text: "Ima-Gun Di" },
  { key: "167", text: "Inquisitors" },
  {
    key: "168",
    text: "Inspector Thanoth",
  },
  { key: "169", text: "Jabba" },
  { key: "170", text: "Jacen Syndulla" },
  { key: "171", text: "Jan Dodonna" },
  { key: "172", text: "Jango Fett" },
  { key: "173", text: "Janus Greejatus" },
  { key: "174", text: "Jar Jar Binks" },
  { key: "175", text: "Jas Emari" },
  { key: "176", text: "Jaxxon" },
  {
    key: "177",
    text: "Jek Tono Porkins",
  },
  { key: "178", text: "Jeremoch Colton" },
  { key: "179", text: "Jira" },
  { key: "180", text: "Jobal Naberrie" },
  { key: "181", text: "Jocasta Nu" },
  { key: "182", text: "Joclad Danva" },
  { key: "183", text: "Joh Yowza" },
  { key: "184", text: "Jom Barell" },
  { key: "185", text: "Joph Seastriker" },
  { key: "186", text: "Jova Tarkin" },
  { key: "187", text: "Jubnuk" },
  { key: "188", text: "Jyn Erso" },
  { key: "189", text: "K-2SO" },
  { key: "190", text: "Kanan Jarrus" },
  { key: "191", text: "Karbin" },
  {
    key: "192",
    text: "Karina the Great",
  },
  { key: "193", text: "Kes Dameron" },
  { key: "194", text: "Ketsu Onyo" },
  { key: "195", text: "Ki-Adi-Mundi" },
  { key: "196", text: "King Katuunko" },
  { key: "197", text: "Kit Fisto" },
  { key: "198", text: "Kitster Banai" },
  { key: "199", text: "Klaatu" },
  { key: "200", text: "Klik-Klak" },
  { key: "201", text: "Korr Sella" },
  { key: "202", text: "Kylo Ren" },
  { key: "203", text: "L3-37" },
  { key: "204", text: "Lama Su" },
  {
    key: "205",
    text: "Lando Calrissian",
  },
  {
    key: "206",
    text: "Lanever Villecham",
  },
  { key: "207", text: "Leia Organa" },
  { key: "208", text: "Letta Turmond" },
  {
    key: "209",
    text: "Lieutenant Kaydel Ko Connix",
  },
  {
    key: "210",
    text: "Lieutenant Thire",
  },
  { key: "211", text: "Lobot" },
  { key: "212", text: "Logray" },
  { key: "213", text: "Lok Durd" },
  { key: "214", text: "Longo Two-Guns" },
  { key: "215", text: "Lor San Tekka" },
  { key: "216", text: "Lorth Needa" },
  { key: "217", text: "Lott Dod" },
  { key: "218", text: "Luke Skywalker" },
  { key: "219", text: "Lumat" },
  { key: "220", text: "Luminara Unduli" },
  { key: "221", text: "Lux Bonteri" },
  { key: "222", text: "Lyn Me" },
  { key: "223", text: "Lyra Erso" },
  { key: "224", text: "Mace Windu" },
  { key: "225", text: "Malakili" },
  { key: "226", text: "Mama the Hutt" },
  { key: "227", text: "Mars Guo" },
  { key: "228", text: "Mas Amedda" },
  { key: "229", text: "Mawhonic" },
  { key: "230", text: "Max Rebo" },
  {
    key: "231",
    text: "Maximilian Veers",
  },
  { key: "232", text: "Maz Kanata" },
  { key: "233", text: "ME-8D9" },
  { key: "234", text: "Meena Tills" },
  { key: "235", text: "Mercurial Swift" },
  { key: "236", text: "Mina Bonteri" },
  { key: "237", text: "Miraj Scintel" },
  { key: "238", text: "Mister Bones" },
  { key: "239", text: "Mod Terrik" },
  { key: "240", text: "Moden Canady" },
  { key: "241", text: "Mon Mothma" },
  { key: "242", text: "Moradmin Bast" },
  { key: "243", text: "Moralo Eval" },
  { key: "244", text: "Morley" },
  { key: "245", text: "Mother Talzin" },
  { key: "246", text: "Nahdar Vebb" },
  { key: "247", text: "Nahdonnis Praji" },
  { key: "248", text: "Nien Nunb" },
  { key: "249", text: "Niima the Hutt" },
  { key: "250", text: "Nines" },
  { key: "251", text: "Norra Wexley" },
  { key: "252", text: "Nute Gunray" },
  { key: "253", text: "Nuvo Vindi" },
  { key: "254", text: "Obi-Wan Kenobi" },
  { key: "255", text: "Odd Ball" },
  { key: "256", text: "Ody Mandrell" },
  { key: "257", text: "Omi" },
  { key: "258", text: "Onaconda Farr" },
  { key: "259", text: "Oola" },
  { key: "260", text: "OOM-9" },
  { key: "261", text: "Oppo Rancisis" },
  { key: "262", text: "Orn Free Taa" },
  { key: "263", text: "Oro Dassyne" },
  { key: "264", text: "Orrimarko" },
  { key: "265", text: "Osi Sobeck" },
  { key: "266", text: "Owen Lars" },
  { key: "267", text: "Pablo-Jill" },
  { key: "268", text: "Padmé Amidala" },
  { key: "269", text: "Pagetti Rook" },
  { key: "270", text: "Paige Tico" },
  { key: "271", text: "Paploo" },
  {
    key: "272",
    text: "Petty Officer Thanisson",
  },
  { key: "273", text: "Pharl McQuarrie" },
  { key: "274", text: "Plo Koon" },
  { key: "275", text: "Po Nudo" },
  { key: "276", text: "Poe Dameron" },
  {
    key: "277",
    text: "Poggle the Lesser",
  },
  { key: "278", text: "Pong Krell" },
  { key: "279", text: "Pooja Naberrie" },
  { key: "280", text: "PZ-4CO" },
  { key: "281", text: "Quarrie" },
  { key: "282", text: "Quay Tolsite" },
  { key: "283", text: "Queen Apailana" },
  { key: "284", text: "Queen Jamillia" },
  { key: "285", text: "Queen Neeyutnee" },
  { key: "286", text: "Qui-Gon Jinn" },
  { key: "287", text: "Quiggold" },
  { key: "288", text: "Quinlan Vos" },
  { key: "289", text: "R2-D2" },
  { key: "290", text: "R2-KT" },
  { key: "291", text: "R3-S6" },
  { key: "292", text: "R4-P17" },
  { key: "293", text: "R5-D4" },
  { key: "294", text: "RA-7" },
  { key: "295", text: "Rabé" },
  { key: "296", text: "Rako Hardeen" },
  {
    key: "297",
    text: "Ransolm Casterfo",
  },
  { key: "298", text: "Rappertunie" },
  { key: "299", text: "Ratts Tyerell" },
  { key: "300", text: "Raymus Antilles" },
  { key: "301", text: "Ree-Yees" },
  { key: "302", text: "Reeve Panzoro" },
  { key: "303", text: "Rey" },
  { key: "304", text: "Ric Olié" },
  { key: "305", text: "Riff Tamson" },
  { key: "306", text: "Riley" },
  { key: "307", text: "Rinnriyin Di" },
  { key: "308", text: "Rio Durant" },
  { key: "309", text: "Rogue Squadron" },
  { key: "310", text: "Romba" },
  { key: "311", text: "Roos Tarpals" },
  { key: "312", text: "Rose Tico" },
  { key: "313", text: "Rotta the Hutt" },
  { key: "314", text: "Rukh" },
  { key: "315", text: "Rune Haako" },
  { key: "316", text: "Rush Clovis" },
  { key: "317", text: "Ruwee Naberrie" },
  { key: "318", text: "Ryoo Naberrie" },
  { key: "319", text: "Sabé" },
  { key: "320", text: "Sabine Wren" },
  { key: "321", text: "Saché" },
  { key: "322", text: "Saelt-Marae" },
  { key: "323", text: "Saesee Tiin" },
  {
    key: "324",
    text: "Salacious B. Crumb",
  },
  { key: "325", text: "San Hill" },
  { key: "326", text: "Sana Starros" },
  { key: "327", text: "Sarco Plank" },
  { key: "328", text: "Sarkli" },
  { key: "329", text: "Satine Kryze" },
  { key: "330", text: "Savage Opress" },
  { key: "331", text: "Sebulba" },
  { key: "332", text: "Senator Organa" },
  { key: "333", text: "Sergeant Kreel" },
  { key: "334", text: "Seventh Sister" },
  { key: "335", text: "Shaak Ti" },
  { key: "336", text: "Shara Bey" },
  { key: "337", text: "Shmi Skywalker" },
  { key: "338", text: "Shu Mai" },
  { key: "339", text: "Sidon Ithano" },
  { key: "340", text: "Sifo-Dyas" },
  { key: "341", text: "Sim Aloo" },
  {
    key: "342",
    text: "Siniir Rath Velus",
  },
  { key: "343", text: "Sio Bibble" },
  { key: "344", text: "Sixth Brother" },
  { key: "345", text: "Slowen Lo" },
  { key: "346", text: "Sly Moore" },
  { key: "347", text: "Snaggletooth" },
  { key: "348", text: "Snap Wexley" },
  { key: "349", text: "Snoke" },
  { key: "350", text: "Sola Naberrie" },
  { key: "351", text: "Sora Bulq" },
  { key: "352", text: "Strono Tuggs" },
  { key: "353", text: "Sy Snootles" },
  {
    key: "354",
    text: "Tallissan Lintra",
  },
  { key: "355", text: "Tarfful" },
  { key: "356", text: "Tasu Leech" },
  { key: "357", text: "Taun We" },
  { key: "358", text: "TC-14" },
  { key: "359", text: "Tee Watt Kaa" },
  { key: "360", text: "Teebo" },
  { key: "361", text: "Teedo" },
  { key: "362", text: "Teemto Pagalies" },
  { key: "363", text: "Temiri Blagg" },
  { key: "364", text: "Tessek" },
  { key: "365", text: "Tey How" },
  { key: "366", text: "Thane Kyrell" },
  { key: "367", text: "The Bendu" },
  { key: "368", text: "The Smuggler" },
  { key: "369", text: "Thrawn" },
  { key: "370", text: "Tiaan Jerjerrod" },
  { key: "371", text: "Tion Medon" },
  { key: "372", text: "Tobias Beckett" },
  { key: "373", text: "Tulon Voidgazer" },
  { key: "374", text: "Tup" },
  { key: "375", text: "U9-C4" },
  { key: "376", text: "Unkar Plutt" },
  { key: "377", text: "Val Beckett" },
  { key: "378", text: "Vanden Willard" },
  {
    key: "379",
    text: "Vice Admiral Amilyn Holdo",
  },
  { key: "380", text: "Vober Dand" },
  { key: "381", text: "WAC-47" },
  { key: "382", text: "Wag Too" },
  { key: "383", text: "Wald" },
  { key: "384", text: "Walrus Man" },
  { key: "385", text: "Warok" },
  { key: "386", text: "Wat Tambor" },
  { key: "387", text: "Watto" },
  { key: "388", text: "Wedge Antilles" },
  { key: "389", text: "Wes Janson" },
  {
    key: "390",
    text: "Wicket W. Warrick",
  },
  { key: "391", text: "Wilhuff Tarkin" },
  { key: "392", text: "Wollivan" },
  { key: "393", text: "Wuher" },
  { key: "394", text: "Wullf Yularen" },
  { key: "395", text: "Xamuel Lennox" },
  { key: "396", text: "Yaddle" },
  { key: "397", text: "Yarael Poof" },
  { key: "398", text: "Yoda" },
  { key: "399", text: "Zam Wesell" },
  { key: "400", text: "Zev Senesca" },
  { key: "401", text: "Ziro the Hutt" },
  { key: "402", text: "Zuckuss" },
]
